package com.app.pojos;

public enum StateType {
	COMILLA,BORISHAL,	CHITTAGONG,NOAKHALI,
	FENI,	RAJSHAHI,MAGURA,	RANGPUR,
	DINAJPUR,TANGAIL,KUSHTIA,
	JHENAIDAH,MANIKGANJ,SYLHET,	
	TEKNAF,SUNAMGANJ,HABIGANJ,KHULNA,	SATKHIRA,
	NARAYANGANJ,NARSINGDI,
}
